[api_keys]
OPENAI_API_KEY="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"
LANGCHAIN_TRACING_V2=true
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGSMITH_API_KEY = "ls__433bbecfd16446e5bd45df0bccd3c4b0"
LANGCHAIN_PROJECT="Streamlit Demo"